PXB-3016 Release notes for Percona XtraBackup 8.0.32-26
percona/pxb-docs pull request #109
Opened 2023-03-14 17:20 UTC by alina-derkach-oaza

modified:   docs/release-notes.md
new file:   docs/release-notes/8.0/8.0.32-26.0.md
modified:   mkdocs-base.yml
modified:   variables.yml

2023-03-21 13:18 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.32-26.0.md
> +This release fixes the security vulnerability [CVE-2022-25834](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25834) issue.
Remove the word issue.

2023-03-21 13:21 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +This release fixes the security vulnerability [CVE-2022-25834](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25834) issue.
fixed

2023-04-03 12:15 UTC, altmannmarcelo requested changes
Add

[PXB-3022](https://jira.percona.com/browse/PXB-3022)

2023-04-03 12:15 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2978](https://jira.percona.com/browse/PXB-2978): Adds a check to skip the Storage Class test if running against MinIO server.
remove this. no real benefit for the user.

2023-04-03 12:15 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. The structure that hol
```suggestion
[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. On write intensive workloads it was causing redo follow thread to fall behind.
```

2023-04-03 12:15 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2970](https://jira.percona.com/browse/PXB-2970): Percona XtraBackup checked redo file at the end of the backup in case using the redo archive.
```suggestion
[PXB-2970](https://jira.percona.com/browse/PXB-2970): Removed unnecessary check for redo log files at the end of backup in case of archive been turned on.
```

2023-04-03 12:15 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-3013](https://jira.percona.com/browse/PXB-3013): The smart memory test failed with 0 redo log because no redo log was applied.
remove

2023-04-03 13:25 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2978](https://jira.percona.com/browse/PXB-2978): Adds a check to skip the Storage Class test if running against MinIO server.
Updated

2023-04-03 13:25 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. The structure that hol
rewritten

2023-04-03 13:25 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-3013](https://jira.percona.com/browse/PXB-3013): The smart memory test failed with 0 redo log because no redo log was applied.
done

2023-04-03 13:25 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2970](https://jira.percona.com/browse/PXB-2970): Percona XtraBackup checked redo file at the end of the backup in case using the redo archive.
Rewritten

2023-04-03 13:26 UTC, alina-derkach-oaza commented
> Add
> 
> [PXB-3022](https://jira.percona.com/browse/PXB-3022)

Added

2023-04-03 13:35 UTC, altmannmarcelo requested changes

2023-04-03 13:35 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. On intensive write wor
```suggestion
[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. On write-intensive workloads, this behavior caused the delay of the redo follow thread.
```

2023-04-03 13:35 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2970](https://jira.percona.com/browse/PXB-2970): Removed unnecessary check for redo log files at the end of backup in case the archive was enabled.
```suggestion
[PXB-2970](https://jira.percona.com/browse/PXB-2970): Removed unnecessary check for redo log files at the end of backup in case the redo archive was enabled.
```

2023-04-03 13:35 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-3022](https://jira.percona.com/browse/PXB-3022): Added more memory to use on prepare phase.
```suggestion
[PXB-3022](https://jira.percona.com/browse/PXB-3022): Reduce the required memory for --prepare phase.
```

2023-04-03 13:46 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-3022](https://jira.percona.com/browse/PXB-3022): Added more memory to use on prepare phase.
Updated

2023-04-03 13:46 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2970](https://jira.percona.com/browse/PXB-2970): Removed unnecessary check for redo log files at the end of backup in case the archive was enabled.
fixed

2023-04-03 13:46 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. On intensive write wor
fixed

2023-04-03 16:21 UTC, altmannmarcelo requested changes

2023-04-03 16:21 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. On intensive write wor
```suggestion
[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. On write-intensive workloads, this behavior caused the delay of the redo follow thread.
```

2023-04-03 16:28 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2979](https://jira.percona.com/browse/PXB-2979): The Smart memory estimation feature parses metadata from the redo log to estimate the required memory to prepare a backup. On intensive write wor
updated

2023-04-03 16:36 UTC, altmannmarcelo approved these changes
LGTM

2023-04-03 16:51 UTC, satya-bodapati requested changes

2023-04-03 16:51 UTC, satya-bodapati commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2998](https://jira.percona.com/browse/PXB-2998): Percona XtraBackup exited during prepare phase at `dict_load_tables_from_space_id()`.
Due to a server bug (https://bugs.mysql.com/bug.php?id=1101) in the upgrade, it leaves the dictionary tables in a temporary schema instead of 'mysql' schema. Percona Xtrabackup can now successfully prepare these backup directories.

2023-04-03 17:04 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2998](https://jira.percona.com/browse/PXB-2998): Percona XtraBackup exited during prepare phase at `dict_load_tables_from_space_id()`.
Updated

2023-04-03 17:15 UTC, patrickbirch approved these changes
Good

2023-04-03 17:15 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2977](https://jira.percona.com/browse/PXB-2977): The paths invoked by decompression tools were not validated before execution. That could cause a security risk.
Remove "That could cause a security risk"

2023-04-03 17:15 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2972](https://jira.percona.com/browse/PXB-2972): Percona XtraBackup crashed instead of exiting gracefully when there was an error after applying a redo and checking the state of redo files.
An error after applying a redo and checking the state of the redo files caused an unexpected exit.

2023-04-03 17:15 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.32-26.0.md
> +[PXB-2954](https://jira.percona.com/browse/PXB-2954): During prepare phase Percona XtraBackup uses SDI to create the METADATA of a table. If there was an orphan table (leftover from a upgrade) withou
uses Serialized Dictionary Information (SDI) to create the table's metadata.

2023-04-04 10:48 UTC, satya-bodapati approved these changes
LGTM!

2023-04-04 13:14 UTC, merged