PXB-3222 Redo the option topics for xtrabackup, xbstream, xbcloud, an…
percona/pxb-docs pull request #233
Opened 2024-01-19 12:37 UTC by patrickbirch

…d xbcrypt (8.0)

	modified:   docs/xbcloud-binary-overview.md
	new file:   docs/xbcloud-options.md
	modified:   docs/xbcloud-swift.md
	modified:   docs/xbcrypt-binary-overview.md
	new file:   docs/xbcrypt-options.md
	modified:   docs/xbstream-binary-overview.md
	new file:   docs/xbstream-options.md
	modified:   docs/xtrabackup-option-reference.md
	modified:   mkdocs-base.yml

2024-01-19 13:17 UTC, alina-derkach-oaza approved these changes
LGTM

2024-01-19 14:26 UTC, satya-bodapati requested changes
I see some text in options misaligned
xtrbackup option reference can be renamed as xtrbackup commandline options (similar to the other two binaries)
braces/brackets at end of each option can be avoided

2024-01-19 16:33 UTC, alina-derkach-oaza commented on docs/xbcloud-swift.md
> +For details on the command-line options,  see the [xbcloud command-line options]
```suggestion
For details on the command-line options, see the [xbcloud command-line options].
```

2024-01-19 16:33 UTC, alina-derkach-oaza commented on docs/xbcloud-swift.md
> +```{.bash
```suggestion
```{.bash data-prompt="$"}
```

2024-01-19 16:33 UTC, alina-derkach-oaza commented on docs/xbcloud-swift.md
> +```{.bash
```suggestion
```{.bash data-prompt="$"}
```

2024-01-19 16:33 UTC, alina-derkach-oaza commented on docs/xbcloud-swift.md
> +```{.bash
```suggestion
```{.bash data-prompt="$"}
```

2024-01-19 16:33 UTC, alina-derkach-oaza commented on docs/xbcrypt-binary-overview.md
> +This utility has been modeled after The [xbstream binary](xbstream-binary-overview.md) to perform encryption and decryption outside of *Percona XtraBackup*. `
```suggestion
This utility has been modeled after the [xbstream binary](xbstream-binary-overview.md) to perform encryption and decryption outside of *Percona XtraBackup*.
```

2024-01-19 16:33 UTC, alina-derkach-oaza commented on docs/xbcrypt-options.md
> +xbcrypt` has following command line options:
```suggestion
`xbcrypt` has the following command line options:
```

2024-01-24 11:28 UTC, satya-bodapati commented
galera-info[¶](https://percona-xtrabackup-docs-8-0-pr-233.onrender.com/xtrabackup-option-reference.html#galera-info)

Usage: --galera-info(

This option creates the xtrabackup_galera_info file which contains the local node state at the time of the backup. Option should be used when performing the backup of Percona XtraDB Cluster. It has no effect when backup locks are used to create the backup.
generate-new-master-key[¶](https://percona-xtrabackup-docs-8-0-pr-233.onrender.com/xtrabackup-option-reference.html#generate-new-master-key)

Usage: --generate-new-master-key(


Two extra braces in the usage.

Rest all looks good Patrick! Thank you for fixing this

2024-01-24 12:34 UTC, alina-derkach-oaza commented on docs/xtrabackup-option-reference.md
> +Make a backup and place it in `--target-dir`. See [Creating a full backup](create-full-backup.md).
```suggestion
Make a backup and place it in `--target-dir`. See [Create a full backup](create-full-backup.md).
```

2024-01-24 12:34 UTC, alina-derkach-oaza commented on docs/xbcrypt-options.md
> +# xbcrypt command-line options
```suggestion
# The xbcrypt command-line options
```

2024-01-24 12:34 UTC, alina-derkach-oaza commented on docs/xbstream-options.md
> +# xbstream command-line options
```suggestion
# The xbstream command-line options
```

2024-01-24 12:34 UTC, alina-derkach-oaza commented on docs/xbcloud-options.md
> +# xbcloud command-line options
```suggestion
# The xbcloud command-line options
```

2024-01-24 12:49 UTC, alina-derkach-oaza approved these changes

2024-01-24 13:04 UTC, merged