PXB-3291 Remove offensive terminology from 8.4 docs (8.4)
percona/pxb-docs pull request #285
Opened 2024-06-03 17:11 UTC by alina-derkach-oaza

modified:   docs/how-xtrabackup-works.md
	modified:   docs/index.md
	modified:   docs/make-backup-in-replication-env.md
	modified:   docs/quickstart-overview.md
	deleted:    docs/release-notes/8.1.0-1.md
	deleted:    docs/release-notes/8.2.0-1.md
	deleted:    docs/release-notes/8.3.0-1.md
	modified:   docs/release-notes/release-notes.md
	modified:   docs/set-up-replication.md
	modified:   docs/xtrabackup-files.md
	modified:   docs/xtrabackup-option-reference.md
	modified:   variables.yml
modified:   docs/flush-tables-with-read-lock.md

2024-06-05 13:46 UTC, patrickbirch approved these changes

2024-08-12 13:58 UTC, satya-bodapati requested changes
xtrabackup options are not changed yet. Please revert them

2024-08-12 13:58 UTC, satya-bodapati commented on docs/set-up-replication.md
> -    It is not recommended to mix MySQL variants (Percona Server, MySQL) in your replication setup. This may produce incorrect `xtrabackup_slave_info` file when adding a new replica.
xtrabackup_slave_info is still there. This means, the offensive terminology file exists and we use it :( Please keep this as is.

2024-08-12 13:58 UTC, satya-bodapati commented on docs/set-up-replication.md
same here, --slave-info option still exists :(

2024-08-12 13:58 UTC, satya-bodapati commented on docs/set-up-replication.md
> +file `xtrabackup_replica_info`, execute the statement for setting up the
revert to slave_info

2024-08-12 13:58 UTC, satya-bodapati commented on docs/set-up-replication.md
> +file `xtrabackup_replica_info`, execute the statement for setting up the
here and everywhere?

2024-08-13 11:26 UTC, satya-bodapati requested changes

2024-08-13 11:26 UTC, satya-bodapati commented on docs/xtrabackup-option-reference.md
> +How many seconds the `--safe-replic-backup` option waits for the `Replic_open_temp_tables` to become zero. The default value is 300 seconds.
safe-slave-backup instead of --safe-replic-backup

2024-08-13 11:26 UTC, satya-bodapati commented on docs/xtrabackup-option-reference.md
> +How many seconds the `--safe-replic-backup` option waits for the `Replic_open_temp_tables` to become zero. The default value is 300 seconds.
Replic/Replica

2024-08-13 11:31 UTC, alina-derkach-oaza commented on docs/set-up-replication.md
> -    It is not recommended to mix MySQL variants (Percona Server, MySQL) in your replication setup. This may produce incorrect `xtrabackup_slave_info` file when adding a new replica.
reverted

2024-08-13 11:31 UTC, alina-derkach-oaza commented on docs/set-up-replication.md
reverted

2024-08-13 11:31 UTC, alina-derkach-oaza commented on docs/set-up-replication.md
> +file `xtrabackup_replica_info`, execute the statement for setting up the
reverted

2024-08-13 11:31 UTC, alina-derkach-oaza commented on docs/xtrabackup-option-reference.md
> +How many seconds the `--safe-replic-backup` option waits for the `Replic_open_temp_tables` to become zero. The default value is 300 seconds.
reverted

2024-08-13 11:50 UTC, satya-bodapati commented on docs/xtrabackup-option-reference.md
> +How many seconds the `--safe-slave-backup` option waits for the `Replic_open_temp_tables` to become zero. The default value is 300 seconds.
typo?: a missing in Replica

2024-08-13 12:11 UTC, alina-derkach-oaza commented on docs/xtrabackup-option-reference.md
> +How many seconds the `--safe-slave-backup` option waits for the `Replic_open_temp_tables` to become zero. The default value is 300 seconds.
fixed

2024-08-13 12:17 UTC, satya-bodapati approved these changes
LGTM!

2024-08-13 13:48 UTC, merged