PXB-3307 Release notes and release note tasks for 8.0.35-31
percona/pxb-docs pull request #289
Opened 2024-06-11 14:01 UTC by patrickbirch

On branch pxb-3307
	modified:   docs/release-notes.md
	new file:   docs/release-notes/8.0/8.0.35-31.0.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-06-11 14:21 UTC, satya-bodapati requested changes

2024-06-11 14:21 UTC, satya-bodapati commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-3283]: When XtraBackup performs a backup and exports a tablespace for tables that have changed their charset-collation before the backup, it creates an incorrect table definition. This incorre
If backup contains tables with temporal datatypes (https://dev.mysql.com/doc/refman/8.0/en/date-and-time-types.html) and their charset/collation changed (ALTER TABLE CONVERT CHARACTER SET) before the backup is taken, xtrabackup export couldn't generate correct configuration (.cfg)files required by the import.

2024-06-11 14:21 UTC, satya-bodapati commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-3130]: During an upgrade, if a type is out of bounds, the Prepare step fails. This means that a value exceeds the expected range, causing the upgrade process to stop and not complete.
when preparing 8.0.30 backups with newer xtrabackup versions, prepare step failed.

2024-06-11 14:21 UTC, satya-bodapati commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-3130]: During an upgrade, if a type is out of bounds, the Prepare step fails. This means that a value exceeds the expected range, causing the upgrade process to stop and not complete.
And please add thank you note to the contributor LiNing and githubid: @LI8023NING

2024-06-11 14:23 UTC, satya-bodapati commented
@patrickbirch we should also add a note that PXB 8.0.35 release (starting from 8.0.34) is upward compatible. People are still unware about this change

2024-06-12 09:00 UTC, satya-bodapati requested changes
minor changes requested

2024-06-12 09:00 UTC, satya-bodapati commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-3130]: when preparing 8.0.30 backups with newer xtrabackup versions, The Prepare step failed. (Thank you to LiNing who contributed)
P in Prepare can be lower case?
The/the?
Thank you LiNing for the contribution!

2024-06-12 09:00 UTC, satya-bodapati commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-3283]: If backup contains tables with [temporal datatypes] (https://dev.mysql.com/doc/refman/8.0/en/date-and-time-types.html) and their charset/collation changed (ALTER TABLE CONVERT CHARACTER
space between (.cfg) and files

2024-06-12 09:00 UTC, satya-bodapati commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-3283]: If backup contains tables with [temporal datatypes] (https://dev.mysql.com/doc/refman/8.0/en/date-and-time-types.html) and their charset/collation changed (ALTER TABLE CONVERT CHARACTER
couldn't prepare vs didn't prepare, please choose the better version, I don't know ;)

2024-06-13 12:08 UTC, satya-bodapati approved these changes
LGTM!

2024-06-13 12:36 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-2797]:  When you import a table with a full-text index from an XtraBackup backup, you might encounter a schema mismatch. This happens when the table's structure in the backup does not match th
[PXB-2797]:  When -> remove extra space

2024-06-13 12:36 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-3130]: when preparing 8.0.30 backups with newer xtrabackup versions, The prepare step failed. (Thank you to LiNing for the contribution!)
when preparing -> When preparing
The prepare step failed - the prepare step failed
(Thank you to LiNing for the contribution!) -> (Thanks to LiNing for the contribution!)

2024-06-13 12:42 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.35-31.0.md
> +* [PXB-2797]:  When you import a table with a full-text index from an XtraBackup backup, you might encounter a schema mismatch. This happens when the table's structure in the backup does not match th
Two "when" words in the sentence.

2024-06-18 13:05 UTC, alina-derkach-oaza approved these changes

2024-06-20 11:32 UTC, merged