PXB-2960 8.0.31-24 Release notes and release note tasks (8.0)
percona/pxb-docs pull request #82
Opened 2023-01-10 13:21 UTC by patrickbirch

Changes to be committed:
	modified:   docs/copyright-and-licensing-information.md
	modified:   docs/release-notes.md
	new file:   docs/release-notes/8.0/8.0.31-24.0.md
	modified:   mkdocs-base.yml

2023-01-18 15:47 UTC, alina-derkach-oaza approved these changes
LGTM

2023-01-19 07:42 UTC, rahulmalik87 requested changes
Can you also mention about  https://jira.percona.com/browse/PXB-2925

2023-01-19 09:48 UTC, patrickbirch commented
PXB-2960 is added.

2023-01-25 11:01 UTC, altmannmarcelo requested changes
Please add:

[PXB-2964](https://jira.percona.com/browse/PXB-2964)
https://jira.percona.com/browse/PXB-2959 - PXB now compiles on platforms with openssl 3.0
https://jira.percona.com/browse/PXB-2971

2023-01-25 11:01 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.31-24.0.md
> +[PXB-2890](https://jira.percona.com/browse/PXB-2890): XtraBackup 8.0 inefficiently compressed already compressed tables.
Its the other way around. It was not compressing which is inefficiently. It now compress compressed tables.

2023-01-25 11:01 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.31-24.0.md
> +[PXB-2928](https://jira.percona.com/browse/PXB-2828): XtraBackup exits with signal 11 when taking a backup.
Link is pointing to a different issue.

2023-01-25 11:01 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.31-24.0.md
> +[PXB-2928](https://jira.percona.com/browse/PXB-2828): XtraBackup exits with signal 11 when taking a backup.
```suggestion
[PXB-2928](https://jira.percona.com/browse/PXB-2928): XtraBackup exits with signal 11 when taking a backup using page tracking.
```

2023-01-25 11:39 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.31-24.0.md
> +[PXB-2890](https://jira.percona.com/browse/PXB-2890): XtraBackup 8.0 inefficiently compressed already compressed tables.
Rewritten.

2023-01-25 11:40 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.31-24.0.md
> +[PXB-2928](https://jira.percona.com/browse/PXB-2828): XtraBackup exits with signal 11 when taking a backup.
Fixed.

2023-01-25 11:50 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.31-24.0.md
> +[PXB-2928](https://jira.percona.com/browse/PXB-2828): XtraBackup exits with signal 11 when taking a backup.
Fixed.

2023-01-25 12:08 UTC, altmannmarcelo approved these changes
LGTM

2023-01-27 08:14 UTC, rahulmalik87 approved these changes

2023-01-27 09:36 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.31-24.0.md
> +    }
Extra ( } ) before </style>

2023-02-07 12:26 UTC, merged