PXB-2984 8.0.32-25 Release notes and release note tasks (8.0)
percona/pxb-docs pull request #95
Opened 2023-02-07 15:50 UTC by patrickbirch

modified:   docs/release-notes.md
	new file:   docs/release-notes/8.0/8.0.32-25.0.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-02-07 15:52 UTC, altmannmarcelo approved these changes
LGTM

2023-02-20 12:19 UTC, alina-derkach-oaza commented on docs/release-notes/8.0/8.0.32-25.0.md
> +c# Percona XtraBackup 8.0.32-25 (2023-02-)
Remove c before #

2023-02-21 09:12 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.32-25.0.md
> +c# Percona XtraBackup 8.0.32-25 (2023-02-)
Done.

2023-02-22 10:48 UTC, satya-bodapati requested changes
https://github.com/percona/percona-xtrabackup/pull/1411/commits

[PXB-2966 - Merge 8.0.32 (Make Instant stable)](https://github.com/percona/percona-xtrabackup/pull/1411/commits/6e2e54d0a6f8b74a0e88af84ff2b9a19bbad1de6)

We have made a decision to consider INSTANT algorithm stable as of
upstream 8.0.32.

PXB now allows instant columns to be present in the backup.

I think we have to document this. Until now, again Oracle MySQL (not PS), PXB refused to take backups if it finds table with instant columns.

From 8.0.32, we remove this limitation and PXB will take backups of MySQL (8.0.32).
We continue to refuse backups until MySQL 8.0.31 with instant columns.

2023-02-22 14:49 UTC, alina-derkach-oaza approved these changes

2023-02-22 15:01 UTC, satya-bodapati approved these changes

2023-02-22 15:04 UTC, altmannmarcelo requested changes

2023-02-22 15:04 UTC, altmannmarcelo commented on docs/release-notes/8.0/8.0.32-25.0.md
> +Percona XtraBackup 8.0.32-25 allows instant columns to be present in the backup for MySQL 8.0.32. The limitation still exists for MySQL 8.0.31 and lower versions.
```suggestion
Starting at Percona XtraBackup 8.0.32-25 allows instant columns to be present in the backup for MySQL 8.0.32. The limitation still exists for backing up MySQL 8.0.31 and lower versions.
The limitation does not exists for backing up Percona Server of any version.
```

2023-02-23 09:54 UTC, patrickbirch commented on docs/release-notes/8.0/8.0.32-25.0.md
> +Percona XtraBackup 8.0.32-25 allows instant columns to be present in the backup for MySQL 8.0.32. The limitation still exists for MySQL 8.0.31 and lower versions.
Rewritten

2023-02-27 13:22 UTC, merged